# Ensures 24-bit truecolor support for Neovim and modern CLI tools
[env]
TERM = "xterm-256color"



# Terminal Font
[font]
size = 13.0

normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Bold Italic" }


[window]
#dimensions = { columns = 120, lines = 35 }
padding = { x = 12, y = 12 }
decorations = "None"
opacity = 0.93
blur = true
startup_mode = "Maximized"
# decorations_theme_variant = "Dark" #Override the variant of the System theme/GTK theme/Wayland client side decorations. Set this to "None" to use the system's default theme variant.


[scrolling]
history = 100000
multiplier = 3


[cursor]
style = { shape = "Block", blinking = "Never" }
blink_interval = 750
unfocused_hollow = true
# thickness = 0.15 # when using beam


[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
{ mouse = "Left", mods = "Control", action = "Copy" },
]


[keyboard]
bindings = [
  {
    key = ",",
    mods = "Control",
    command = {
      program = "gnome-text-editor",
      args = ["/home/smjohn/.config/alacritty/alacritty.toml"]
    }
  }
]


[general]
import = [
  "everforest_dark_hard-mine.toml"
]

live_config_reload = true


